# Generated by Django 3.2.9 on 2022-02-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_ticket_has_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='body',
            new_name='ticket_body',
        ),
    ]
